# Skapa Dark Theme 
# Default colors
[colors.primary]
background = '#111111' # --colour-static-black
foreground = '#eeeeee' # --colour-text-and-icon-1

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#111111'   # --colour-static-black
red = '#EC773E'     # --colour-commercial-message-bti-red
green = '#7FC76D'   # --colour-semantic-positive
yellow = '#FFDB01'  # --colour-commercial-message-bti-yellow
blue = '#489CE3'    # --colour-semantic-informative
magenta = '#ED5A51' # --colour-commercial-message-new-lower-price
cyan = '#3FB1E1'    # --colour-commercial-message-ikea-family
white = '#eeeeee'   # --colour-text-and-icon-1

# Bright colors
[colors.bright]
black = '#111111'   # --colour-static-black
red = '#EC773E'     # --colour-commercial-message-bti-red
green = '#7FC76D'   # --colour-semantic-positive
yellow = '#FFDB01'  # --colour-commercial-message-bti-yellow
blue = '#489CE3'    # --colour-semantic-informative
magenta = '#ED5A51' # --colour-commercial-message-new-lower-price
cyan = '#3FB1E1'    # --colour-commercial-message-ikea-family
white = '#eeeeee'   # --colour-text-and-icon-1

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

